// Centralized content management for OBUMBRAVIT Terminal
// This ensures consistency across all generated content

export interface ProfileData {
  name: string
  title: string
  experience: string
  email: string
  github: string
  linkedin: string
  twitter: string
  currentRole: string
  availability: string
}

export const PROFILE_DATA: ProfileData = {
  name: 'OBUMBRAVIT',
  title: 'Full-Stack Developer & iOS Specialist',
  experience: '6+ Years',
  email: 'hello@obumbravit.com',
  github: 'github.com/obumbravit',
  linkedin: 'linkedin.com/in/obumbravit',
  twitter: '@obumbravit',
  currentRole: 'Employed Full-Stack Developer',
  availability: 'Limited (Currently employed)'
}

export interface TechStack {
  ios: string[]
  web: string[]
  desktop: string[]
  databases: string[]
  tools: string[]
}

export const TECH_STACK: TechStack = {
  ios: ['Swift', 'SwiftUI', 'Objective-C', 'UIKit'],
  web: ['React', 'Next.js', 'TypeScript', 'JavaScript', 'HTML5', 'CSS3'],
  desktop: ['Various frameworks and languages'],
  databases: ['PostgreSQL', 'MongoDB', 'SQLite'],
  tools: ['Git', 'Docker', 'Xcode', 'VS Code']
}

export interface Skills {
  ios: number
  web: number
  desktop: number
  uiux: number
  api: number
  database: number
  performance: number
  architecture: number
}

export const SKILLS: Skills = {
  ios: 95,
  web: 92,
  desktop: 88,
  uiux: 90,
  api: 93,
  database: 87,
  performance: 89,
  architecture: 91
}

export interface Services {
  ios: string
  web: string
  desktop: string
  uiux: string
  api: string
  architecture: string
  performance: string
}

export const SERVICES: Services = {
  ios: 'iOS Development (Swift/SwiftUI)',
  web: 'Full-Stack Web Development',
  desktop: 'Desktop Application Development',
  uiux: 'Modern UI/UX Design',
  api: 'API Development & Integration',
  architecture: 'System Architecture',
  performance: 'Performance Optimization'
}

export const SYSTEM_INFO = {
  version: 'v2.1.0',
  name: 'OBUMBRAVIT_OS',
  terminal: 'OBUMBRAVIT_TERMINAL'
}

export const BOOT_MESSAGES = [
  'Initializing system...',
  'Loading kernel modules...',
  'Mounting filesystems...',
  'Starting network services...',
  'Loading development environment...',
  'Initializing iOS development tools...',
  'Starting web development stack...',
  'Loading desktop development tools...',
  'Establishing GitHub integration...'
]

export const FOOTER_TEXT = '*Generated by OBUMBRAVIT_TERMINAL*'

// Utility functions for consistent content generation
export const formatDate = (date: Date = new Date()) => date.toISOString()
export const formatUptime = () => Math.floor(Date.now() / 1000)
export const formatSkills = (skills: Skills) => 
  Object.entries(skills).map(([skill, level]) => `- **${skill.charAt(0).toUpperCase() + skill.slice(1)}**: ${level}%`).join('\n')

export const formatTechStack = (stack: TechStack) => {
  return Object.entries(stack).map(([category, techs]) => 
    `- **${category.charAt(0).toUpperCase() + category.slice(1)}**: ${techs.join(', ')}`
  ).join('\n')
}

export const formatServices = (services: Services) => 
  Object.values(services).map(service => `- ${service}`).join('\n')
